### ISSUE TITLE
name change?

### ISSUE THREAD

**Issue by jippi** [cakephp/chronos#1]
There is another wildly popular piece of open source software from mesos called chronos as well...  ( https://github.com/mesos/chronos ) 

Maybe we should consider another name to avoid google clashes?

**Comment by lorenzo** [comment]
If you have suggestions we would be interested to know. Nowadays any non-random string will clash with another project. We were actually aware of that cron library before we picked the name, but decided the reals are different enough so it wouldn't be a problem

**Comment by josegonzalez** [comment]
`DateTime` is a good one.

**Comment by dereuromark** [comment]
@josegonzalez Too easy to confuse with the PHP core one IMO. I think Chronos is just fine.

**Comment by jadb** [comment]
I agree with @jippi about trying to avoid google clashes - but if we can't well so be it, chronos is nice anyways. 

Here are some suggestions:

- term
- era
- pace

**Comment by jadb** [comment]
After I typed this I thought that as @lorenzo mentioned any name would clash so we users would end up anyways having to use at least 'php' (maybe even 'cakephp') to narrow their search results (which would work the same for chronos).

**Comment by josegonzalez** [comment]
Chronos is good then, lets keep it. Last thing we need to be arguing about is naming.

**Comment by markstory** [comment]
Epoch is another good time related name. It hasn't been [grabbed on packagist](https://packagist.org/search/?q=epoch) yet either.

**Comment by josegonzalez** [comment]
Okay epoch do it

**Comment by ADmad** [comment]
Chronos sounds better to me :)  I don't think a lib with same name in a different language should cause any confusion.
