### ISSUE TITLE
Make subMonth work correctly

### ISSUE THREAD

**Issue by dereuromark** [cakephp/chronos#10]
See https://github.com/briannesbitt/Carbon/issues/428

I think it is worth fixing the faulty (unintuitive) behavior of PHP, and making subMonth() work as expected.
To make sure the former behavior can also be used if desired, we could provide a method `addMonthsExact()` or `addMonthsOverflow()`.

What do you think?
Since the lib is new we do have the change to do that without breaking user land code.

**Comment by lorenzo** [comment]
When hitting the overflow, what should be the day of the month at the end of the operation? The last day of the month?

**Comment by markstory** [comment]
@lorenzo Yes. Having dealt with this shenanigans at work, going to the end of the month is what our customers expected.

**Comment by lorenzo** [comment]
Sounds good, I can take care of this
