### ISSUE TITLE
Please don't stripp microseconds as this is wrong behaviour.

### ISSUE THREAD

**Issue by mvrhov** [cakephp/chronos#116]
#112 is a wrong fix for #111 as striping microseconds is just plain wrong.
I'm integrating chronos into a pomm and the test suite fails when using ChronosWhere the tests with DateTime will pass. And I'm testing this on 7.0

The 2nd issue is that stripping them also strips TZ info.

```php
new \DateTime('2014-09-29 18:24:54.591767+02:00'),
new \DateTime('2014-07-29 14:50:01+02:00'),
new \DateTime('2012-12-14 04:17:09.063948+01:00'),

"2014-09-29 18:24:54.591767+02:00",
"2014-07-29 14:50:01.000000+02:00",
"2012-12-14 04:17:09.063948+01:00"

new Chronos('2014-09-29 18:24:54.591767+02:00'),
new Chronos('2014-07-29 14:50:01+02:00'),
new Chronos('2012-12-14 04:17:09.063948+01:00'),

"2014-09-29 18:24:54.000000+00:00",
"2014-07-29 14:50:01.000000+00:00",
"2012-12-14 04:17:09.000000+00:00"
```

**Comment by markstory** [comment]
microseconds are only stripped when creating `Date` instances which have no time components at all. `Chronos` doesn't invoke this method at all, there must be a different issue.

**Comment by markstory** [comment]
I added a passing test in  0c3ad86b903182470575bc9d2d1c8f52b6784537 that covers the problem you're having. Are you using `Cake\Chronos\Date` by any chance?

**Comment by mvrhov** [comment]
I'm sorry, but it seems that I had an hard to find error when I adapted the tests to also support Chronos. Thanks for prompt support.
