### ISSUE TITLE
RFC - Split up DateTimeTrait into smaller traits

### ISSUE THREAD

**Issue by markstory** [cakephp/chronos#12]
The current DateTimeTrait is over 2000 lines long. I was wondering if people would be up to splitting up the mega trait into a few smaller traits. I see a few types of methods:

* Formatting methods. (toRssString) etc.
* Modifiers (endOfWeek, startOfDay, addSecond, addMinute, lastOfMonth) etc.
* Comparisons (isToday, isThisYear, isThursday) etc.
* Operators (eq, neq, lt, lte, gt, gte)
* Timezones (tz, timezone)

I think splitting up the mega trait will help with composability when we make a calendar date object.

**Comment by dereuromark** [comment]
Great idea!

**Comment by lorenzo** [comment]
Makes sense to me

**Comment by markstory** [comment]
Finished with #21
