### ISSUE TITLE
phpstan included

### ISSUE THREAD

**Issue by dereuromark** [cakephp/chronos#121]
I think similar to other projects including phpstan here would be really good in terms of code quality.

cc @ondrejmirtes

**Comment by ondrejmirtes** [comment]
I'm all for that 😊 I can prepare a PR or supervise one.

**Comment by markstory** [comment]
Sounds fine to me.

**Comment by ondrejmirtes** [comment]
I opened a PR: #127

**Comment by dereuromark** [comment]
Great, closing this issue then.
