### ISSUE TITLE
ModifierTrait.php Spanish and other lenguages 

### ISSUE THREAD

**Issue by Oxicode** [cakephp/chronos#128]
Hola

¿Pueden hacer que los textos sean en español?

```
trait ModifierTrait
{
    /**
     * Names of days of the week.
     *
     * @var array
     */
    protected static $days = [
        ChronosInterface::MONDAY => 'Monday',
        ChronosInterface::TUESDAY => 'Tuesday',
        ChronosInterface::WEDNESDAY => 'Wednesday',
        ChronosInterface::THURSDAY => 'Thursday',
        ChronosInterface::FRIDAY => 'Friday',
        ChronosInterface::SATURDAY => 'Saturday',
        ChronosInterface::SUNDAY => 'Sunday',
    ];
```

**Comment by markstory** [comment]
@Oxicode Why do these values need to be translated? They are generally used to to modify dates via `modify()` which only accepts english values.

**Comment by Oxicode** [comment]
Código:

![image](https://cloud.githubusercontent.com/assets/1320709/22838238/4468c3fc-ef92-11e6-82ae-91b22839cea1.png)

Imprime:

![image](https://cloud.githubusercontent.com/assets/1320709/22838232/3fe8304c-ef92-11e6-9a86-975e7e54de05.png)


Pero debería salir:
```
Viernes
Vie
Febrero
```

**Comment by markstory** [comment]
Unfortunately that is a function of how PHP works. The `DateTime::format()` method does not support translated data. Instead you might want to look at using the intl features that CakePHP offers, as translating strings is outside he scope of Chronos.
