### ISSUE TITLE
RFC - Add a Calendar date object

### ISSUE THREAD

**Issue by markstory** [cakephp/chronos#13]
One of the issues we've heard a bunch of times with the ORM is that DATE columns are mapped to datetime instances. While we can't completely avoid that, we could make a 'calendar' date object. This object would differ from the datetime instance in a few ways:

* The time methods would be removed or raise errors.
* The time mutators would raise errors or not exist. Including the methods and raising exceptions lets us conform to the ChronosInterface which is nice.
* On construction the time component would be set to `00:00:00`.

**Comment by HavokInspiration** [comment]
Good idea.
I often had to manipulate "calendar" date and having something dedicated to that would be super nice.

As for the various points, I'd rather have errors raised rather than methods removed. I think that would avoid confusion to have a clear error message stating that the methods can't be used and that if the "time component" is needed, the wrong object is being used.

**Comment by lorenzo** [comment]
:+1:

**Comment by markstory** [comment]
@HavokInspiration Ok. Given the scope of the chronosinterface, we'll need to raise exceptions anyways.

**Comment by HavokInspiration** [comment]
@markstory All good then ! (I just checked the ChronosInterface... It is quite lengthy).

**Comment by robertpustulka** [comment]
BTW It's rather not very OOP to have interfaces over 1000 lines long...

**Comment by lorenzo** [comment]
I'm not sure it is a good idea to throw exceptions in those methods. If we do then we need to make every other class aware of the differences between a normal datetime and a calendar date.

**Comment by markstory** [comment]
@robertpustulka DateTimes are all knowing all powerful objects :wine_glass:

**Comment by robertpustulka** [comment]
@markstory I was thinking that maybe we could split ChronosInterface into TimeInterface and CalendarInterface, but what about compatibility with DateTimeInterface then? 
Need to remind myself that PHP5 is not very OOP either :)

**Comment by markstory** [comment]
Breaking interfaces up might be an option. Once I'm done splitting the megatrait up, I'll get started on this.

**Comment by dereuromark** [comment]
How about having Time and Date then as classes?

```php
use Cake\Chronos\Time;
use Cake\Chronos\Date;

$time = new Time();
$date = new Date();
```
so Chronos class itself => rename to Time, adding Date, both extending \DateTime then.
That would also get rid of the double name in `use Cake\Chronos\Chronos` and make it more clear what those two splits refer to.

**Comment by markstory** [comment]
I think DateTime and Date are reasonable classes to have. A Time only class is less useful in my mind, as it implies the class would only manage clock time (without a date aspect).

**Comment by dereuromark** [comment]
We (in CakePHP core) also have a Time class and it is pretty clear to all that it also manages Date along with the Time. It would be less confusing than having a DateTime besides the core one maybe?
