### ISSUE TITLE
DST handling while date modifying

### ISSUE THREAD

**Issue by Ovsyanka** [cakephp/chronos#135]
Hello!

What do you think about implement the same DST handling like i suggested in [issue](https://github.com/briannesbitt/Carbon/issues/883) for Carbon?

For example i have the date `2014-03-30 00:00:00` in `Europe/London` (`new Carbon('2014-03-30 00:00:00, 'Europe/London')`), then if i want to increase date by 1 day, i expect `2014-03-31 00:00:00`, but if want to increase date by 24 hours, then i expect `2014-03-31 01:00:00`, because in this timezone there will be that time after 24 hours (timezone offset changes because of Daylight correction). The same for minutes and seconds.

As i see, in chronos:

```php
$date = new Chronos('2014-03-30 00:00:00', 'Europe/London');
$date = $date->modify('+86400 sec');
$this->assertSame('2014-03-31 01:00:00 +01:00', $date->format('Y-m-d H:i:s P'));

// failed:
// -2014-03-31 01:00:00 +01:00
// +2014-03-31 00:00:00 +01:00
```

If you agree with me i will write pull-request.

**Comment by markstory** [comment]
I think what you've outlined makes sense to me. Advancing by hours, minutes or seconds and crossing the DST boundary should take the DST transition into account, as the transition happened, and a 'bonus' hour was gained/lost.

**Comment by Ovsyanka** [comment]
Okay, i will prepare pull-request in a few days.

**Comment by Ovsyanka** [comment]
I have new thoughts about the issue. Please look to issue in Carbon project: https://github.com/briannesbitt/Carbon/issues/883#issuecomment-339446962

**Comment by markstory** [comment]
It sounds like you're proposing to effectively revert the previous set of changes. I may have misunderstood the discussion thread in Carbon though.

**Comment by Ovsyanka** [comment]
Not exactly revert. I am not sure about decision we standed to change how `modify` method works itself. Instead I suggeted to move that changes particulary in `add|sub` methods of `Carbon` (and `Chronos`), only the `sec|minute|hour` ones.

In addition I [realised](https://github.com/briannesbitt/Carbon/pull/884#discussion_r145051548), that my current code isn't perfect right now and it runs when `ordinal unit` `second` used, not only `time unit` `second`.

Besides that I investigate independent bug, that with negative time changing to skipped time period (between 1:00 and 2:00) the time changing to +1 hour instead -1 hour.

**Comment by itsjavi** [comment]
> Advancing by hours, minutes or seconds and crossing the DST boundary should take the DST transition into account

But what happens when you advance in days or other time units that are not in the regular expr. and cross the DST boundary? I am not sure if the fix will work then..

**Comment by Ovsyanka** [comment]
@itsjavi Some people expects that if they add a day - there will bi the same time in the new offset. By default php trying to do that thing, (but it doing it wrong in some cases). Initially idea is that most people expecting default php logic when units is >= day and in the same time it is quite unexpected with smaller units.

So, answer to your question: For other units PHP default behavior happens.

**Comment by Ovsyanka** [comment]
@markstory, @itsjavi I realised (in result of discussion https://github.com/briannesbitt/Carbon/issues/883#issuecomment-357393640) that my approach was wrong. Because to all users expect the same behavior of modify in matter of handling DST changes. There is usecases for both approaches in both diapasones of units (less than day and equal or bigger). And by default php already have the way to handle this. You just should
* use UTC timezone if you don't want to have timestamp adjusments in case of DST changes
* use non-UTC timezone if you want to have such adjustments

So I suggest to revert my changes. I can do it, just need your approve.

And, maybe it is a good idea to add some info about this stuff into the library documentation. But I don't know where to add this and how to describe this issue. If someone will do it I could check it and fix the facts if it will be needed.

**Comment by markstory** [comment]
> So I suggest to revert my changes. I can do it, just need your approve.

A revert pull request would be great. As for the documentation, could this type of caveat be part of the API documentation?

**Comment by Ovsyanka** [comment]
Yes, of course. But I don't know where to place it in the API docs.

**Comment by markstory** [comment]
I just noticed the lack of good places to put the API docs now that the method is being removed. The next best place is in the cakephp book which has documentation guides for chronos.

**Comment by Ovsyanka** [comment]
Let's be the book then. I still don't know where exactly and how (wich repo?) to place it there. Maybe it will be better you to do it?

**Comment by saeideng** [comment]
book:
https://book.cakephp.org/3.0/en/chronos.html
https://github.com/cakephp/docs/blob/3.0/en/chronos.rst

**Comment by othercorey** [comment]
Sorry for pinging an old thread, but since it is still open is there a 2 sentence summary of what the behavior is and if/why it is correct?

**Comment by Ovsyanka** [comment]
Here it is: https://github.com/cakephp/chronos/issues/135#issuecomment-357763047

All changes related to this issue are reverted.

**Comment by othercorey** [comment]
@Ovsyanka Thanks!  Chronos behavior is following php's behavior which sounds good for now.
