### ISSUE TITLE
Timezone argument ignoring in constructors

### ISSUE THREAD

**Issue by Ovsyanka** [cakephp/chronos#136]
`Date`|`MutableDate`|`MutableDateTime` ignores `$tz` argument and forces it to 'UTC', but `Chronos` handling it. It seems wierd for me. I think it is better to handle it in all constructors in the same way (not ignore it). What do you think?

**Comment by markstory** [comment]
Date and MutableDate intentionally ignore the timezone as calendar dates have no timezone. January 10 exists in all timezones.

MutableDateTime however should be respecting the provided timezone. Do you have an example of it not doing that?

**Comment by Ovsyanka** [comment]
Seems like i made a mistake and `MutableDateTime` handles `$tz` argumens.

About `Date`|`MutableDate` i got your point.

**Comment by markstory** [comment]
I'll see if we can remove the unused argument without triggering E_STRICT warnings.
