### ISSUE TITLE
Add API docs to api.cakephp.org

### ISSUE THREAD

**Issue by markstory** [cakephp/chronos#14]
We'll need to figure out how to get some public facing API docs for this project before 1.0.

I'm thinking something like http://api.cakephp.org/chronos/1.0/* as a URL.  This might also be a way to add API docs for migrations, bake, and elasticsearch.

**Comment by ADmad** [comment]
Sounds good. Cake's docs should also probably be moved under http://api.cakephp.org/cakephp/*  which http://api.cakephp.org redirecting to latest version.

**Comment by markstory** [comment]
We would have to keep the existing urls as aliases so we don't lose any google juice.

**Comment by markstory** [comment]
Pull request up for the API docs cakephp/cakephp-api-docs#38. Once merged, I'll need to do some jenkins work.

**Comment by markstory** [comment]
Done now.
