### ISSUE TITLE
Different date is returned for Chronos::today($tz) and Date::today($tz)

### ISSUE THREAD

**Issue by stil** [cakephp/chronos#149]
Currently here is 18 Jul, 1:31 AM in Europe/Warsaw (UTC+2:00).
For some reason ```Chronos::today()``` and ```Date::today()``` return different date.

```php
Chronos::today("Europe/Warsaw")
```
```
Cake\Chronos\Chronos {#306
  +"time": "2017-07-18 00:00:00.000000"
  +"timezone": "Europe/Warsaw"
  +"hasFixedNow": false
}
```

```php
Date::today("Europe/Warsaw")
```
```
Cake\Chronos\Date {#306
  +"date": "2017-07-17"
  +"hasFixedNow": false
}
```

Am I missing something or is it a bug?

**Comment by markstory** [comment]
Date objects always use UTC as their timezone, ignoring the input timezone. In this scenario it might make sense to get the date in Warsaw and then create another instance in utc for the same calendar day.

**Comment by davispuh** [comment]
> ```
> Date::today("Europe/Warsaw")
> ```

The problem with `Date` is that it doesn't have any particular timezone, but it should have it. There can be a day difference due to timezones. For example comparing `Date` from `PDT` and `Date` from `AEST`.
So that above is same as `Date::today(new DateTimeZone('UTC'))` which obviously won't match `Chronos($tz)` because `Date` always ignores `tz`.

Currently using `Date` with different timezones is real PITA.

```php
$timestamp = 1565679600; // 2019-08-13 00:00:00 PDT

// need to do this to get date of specific timezone from unix timestamp
$timezone1 = new DateTimeZone('America/Los_Angeles');
$dateTime1 = Chronos::createFromTimestamp($timestamp, $timezone1);
$date1 = Date::instance($dateTime1);

$timezone2 = new DateTimeZone('Australia/Sydney');
$date2 = Date::instance(Chronos::createFromTimestamp($timestamp, $timezone2));

// we want to compare if 2 dates from different timezones are on same day
if ($date1 == $date2) {
  // they're on same day
} else {
  // different days
}

// we want to compare Date to DateTime where each has different timezone
// but we can't use $date2 directly because it doesn't have info about it's timezone
$date2WithTimezone = Chronos::createFromTimestamp($date2->getTimestamp(), $timezone2);
if ($date2WithTimezone > $dateTime1) {

}

```

**Comment by markstory** [comment]
If you need dates in timezones the Date class in this package is not going to work. It is intended to represent a calendar day. Much like the date column type in Mysql or postgres. You might be better served by using timezone aware datetime objects.

**Comment by davispuh** [comment]
It would be good if it knew about timezones, without them it's not that useful. Like I want to work with calendar dates but location is important. If I use Chronos/DateTime then I don't get Date feature with time always being 00:00

**Comment by markstory** [comment]
I'm still not sure that timezones on calendar dates are a simple. For example, 10:00 EDT == 17:00 in Turkey (Same day). However, 15:00 EDT is 2:00 Turkey (different days). Without a time component calendar days cannot move between timezones accurately.

**Comment by othercorey** [comment]
I am wondering if `Date` should even have `today()` and 'tomorrow()` and even 'now()` factory methods.  

The `Date` documentation does not state that it is an UTC DateTime object.  Instead it states that it represents a calendar date.  That shouldn't mean it is a "calendar date in utc".

**Comment by othercorey** [comment]
This now works the same.  The default time zone is used unless a time zone is specified.
