### ISSUE TITLE
Multiple instance created if calling certain methods.

### ISSUE THREAD

**Issue by votemike** [cakephp/chronos#150]
If calling `isPast()`, `isToday()`, `isFuture()` on a Chronos object, a new static of "now" is created on each method call in order to compare.  
I believe there must be a way to cache a "now" for reuse to avoid creating many unnecessary objects.

**Comment by markstory** [comment]
How would caching 'now' work? What is 'now' could change throughout the duration of a PHP process.

**Comment by votemike** [comment]
I was wondering the same thing. Unfortunately I could not think of a decent solution. However I imagine in 99% of cases I would have thought that during a single process people would expect 'now' to be the same.
Maybe have a new variable that can be set to true if you wish to use 'now caching' in a similar way that  `$testNow` can be set until unset. That way the default behaviour stays as expected, but if someone wishes to optimise their calls they can.
So someone could call `Chronos::setCacheNow(true);` or something like that.
What are your thoughts?

**Comment by dereuromark** [comment]
The main issue with multiple "now" during a PHP dispatching process is a more severe one:
The leap seconds. If the seconds cross over from lets say 15 to 16, and you didnt store the created now value in a variable the first time to reuse, they would have a different time.
For this there is a setTest() mode.
Having a setNowFixed() sounds like a similar thing then for production.
Not sure what the implications of it are, however. But could be valuable from this point of view.
I am not sure about the speed benefit etc, if it would be really that much of a gain from that point of view.

**Comment by votemike** [comment]
I did a quick benchmark test calling `isPast()`, `isToday()` and  `isFuture()` one after another 100000 times. Which seemed to take about 11 seconds. I then hacked together a something that returned a cached instance inside `::now()` instead of a new instance which seemed to take the benchmark down to around 7 seconds. If those numbers are correct it seems worthwhile to me.

**Comment by votemike** [comment]
I could put a PR in for my benchmark file if you like.

**Comment by markstory** [comment]
What would cachedNow() do different than testNow() does?  They both sound like ways to fixate 'now'.

**Comment by votemike** [comment]
Even if `testNow()` is set... when `isToday()` is called, a new instance is created. I would imagine the `now()` method would bypass `new static('now', $tz)` and instead return this cached instance of "now".

**Comment by dereuromark** [comment]
@markstory setTestNow() can accept a custom date time string to set it to e.g. some value in the past or future for specific tests.
That's what we sure don't want to allow for production :)
So a new method would have to be added either way that can only use the current time (accepts only bool true/false to enable/disable).

**Comment by markstory** [comment]
So if we were to add a new fixed now, how would that method interact with testNow()?

**Comment by lorenzo** [comment]
I don't think it is possible to cache the current time without introducing new bugs.

We could instead offer a specialised object that has the current time cached and document it as meant to be used in tight loops for doing comparisons of this type:

```php
$comp = new FrozenTimemark();

foreach ($results as $r) {
    if ($r->isToday($comp)) {
        ...
    }
}
```

That way we avoid the issues of magically caching the current time and solve the performance issue. The only problem is someone using the `FrozenTimemark` in a long running script, but we could maybe document agains using it like that

**Comment by dereuromark** [comment]
+1 for *mark :trollface:
