### ISSUE TITLE
Convenience Functions for choosing/setting precision

### ISSUE THREAD

**Issue by ravage84** [cakephp/chronos#152]
After reading a [recent article about time precision](http://rosstuck.com/precision-through-imprecision-improving-time-objects), I was wondering if it would make sense to include convenience functions for choosing/setting precision into Chronos?

I could imagine setting the precision of a date or datetime object to:
- year
- half year
- quarter
- month
- week
- day
- half day
- hour
- half an hour
- quarter hour
- minute
- second

Creating two datetime objects, setting their precision and comparing them could become quite easy...
Some of that might be possible already through one wary or another.

Alternatively, instead of functions, this could be implemented through different precision classes.

May be all this is just a brain fart. Let me know.

**Comment by markstory** [comment]
We have a number of comparison methods that would fall under 'solution 3' from that article. How do you see these precision methods being used?

**Comment by ravage84** [comment]
```` php
// With methods
$now = Chronos::now();
$nowPreciseToHour = $now->setPrecisionToHour();
$someOtherDate = Chronos::create(2017, 12, 25, 4, 32, 58);
$otherDatePreciseToHour = $someOtherDate->setPrecisionToHour();

// With different types
$nowPreciseToHour = ChronosHour::now();
$otherDatePreciseToHour = ChronosHour:parse($someStringToParse);
````

Instead of working with one of the ``diffInXyz()`` methods, you can compare apple with apple.

**Comment by ravage84** [comment]
Eric Evans proposes an interesting solution to problems like this in this [talk "Eploring Time"](https://www.youtube.com/watch?v=Zm95cYAtAa8&feature=youtu.be&t=41m52s):
[Allen's interval algebra](https://en.wikipedia.org/wiki/Allen%27s_interval_algebra)

But a solution like the one proposed would probably go way too far and would likely be implemented on a programming language level at best.
