### ISSUE TITLE
addYear and leap years

### ISSUE THREAD

**Issue by digilist** [cakephp/chronos#157]
When I call `addYear` on a 29th of February I'd expect to stay in the same month and have the 28th of February in the next year, however the result is the first of March.

```php
// Expected: 2013-02-28 12:00:00.000000
var_dump((new \DateTime('2012-02-29 12:00:00'))->modify('+1 year')); // 2013-03-01 12:00:00.000000
var_dump((new Chronos('2012-02-29 12:00:00'))->addYear(1)); // 2013-03-01 12:00:00.000000
```

Chronos got the same behavior when using addMonth:
```php
var_dump((new \DateTime('2014-05-31 12:00:00'))->modify('+1 month')); // 2014-07-01 12:00:00.000000
var_dump((new Chronos('2014-05-31 12:00:00'))->addMonth(1)); // 2014-06-30 12:00:00.000000
```

I can provide a pull request if there aren't any objections to changing this.

**Comment by markstory** [comment]
I'm concerned with deviating from the behavior that PHP's core DateTime implementation provides. This makes the behavior of Chronos harder to grok as it does the opposite of what PHP does.

**Comment by chinpei215** [comment]
Since we have `addMonth()` and `addMonthsWithOverflow()`, I think adding `addYearsWithOverflow()` makes sense.

**Comment by markstory** [comment]
Closing as there is a pull request now.
