### ISSUE TITLE
Problems with testing with microseconds

### ISSUE THREAD

**Issue by mumia** [cakephp/chronos#160]
I'm running a PHP 7.2 server.

And although I have set the "testNow" variable:
```
Chronos::setTestNow(Chronos::now());
```

I'm having problems when testing:
```
'created' => Authored Object (
         'by' => 6eeaf6b5-ce76-4d15-b370-5e148b93c8db
-        'on' => 2018-02-01T12:31:39.260470+0000
+        'on' => 2018-02-01T12:31:38.889742+0000
)
```

Both dates where generated with the Chronos::now() after the "setTestNow".

Might I be doing something wrong?

**Comment by markstory** [comment]
I'll try to reproduce this. What version of chronos are you using?

**Comment by mumia** [comment]
@markstory I am currently on version ```1.1.4```.
The code is running in a docker with the image ```php:7.2-fpm-alpine```.

**Comment by mumia** [comment]
Apparently this problem has to do with the fact the I'm calling the "setTestNow" in several tests.
I tried moving the "setTestNow" to the test case constructor and it seems to work fine.
Of course this would not be the best solution because I will eventually need to set some custom date in a test.

**Comment by markstory** [comment]
Each time you setTestNow() you'll likely get new microseconds. In your tests where you set a custom date how are you doing it?

**Comment by mumia** [comment]
I'm using (for now):
```
Chronos::setTestNow(Chronos::now());
```

**Comment by mumia** [comment]
I think I figured it out.
The fixture system I'm using was creating the fixture set on object instantiation. And this happens inside the container, well before I call the "setTestNow".

By tweaking the fixtures to load only when requested I am able to run everything without any strange date behaviour.
