### ISSUE TITLE
Wrong months ?

### ISSUE THREAD

**Issue by agarzon** [cakephp/chronos#170]
```php
$date = Chronos::create()->year(2018)->month(6)->startOfMonth()->startOfDay();
debug($date);
```

It returns:
```
object(Cake\Chronos\Chronos) {

	'time' => '2018-07-01 00:00:00.000000',
	'timezone' => 'UTC',
	'hasFixedNow' => false

}
```

It should be JUNE, not July... same happens with February and other few.

Using UTC tz in server and PHP, times are synced.
Using cakephp 3.5.17 with PHP 7.1.14

**Comment by dereuromark** [comment]
check API for withOverflow methods.

**Comment by agarzon** [comment]
Well, the same issue happens using **Time**, doing it as documentation suggest. https://book.cakephp.org/3.0/en/core-libraries/time.html

```php
        $now = Time::now();
        $now->year = 2018;
        $now->month = 6;
        debug($now);
```
it returns as July.

The withOverflow as I can see are for add and subtract from a specific time, my need is to actually set a specific time.

**Comment by agarzon** [comment]
As additional info, the only method I found that respect the correct month's sequence was setDate()

```
$now->setDate(2018, 6, 1)->startOfDay();
```

It returns:
```
object(Cake\I18n\Time) {

	'time' => '2018-06-01T00:00:00-00:00',
	'timezone' => 'UTC',
	'fixedNowTime' => false

}
```

**Comment by markstory** [comment]
Not much we can do here as the date instance is initially created as `2018-05-31'. When you change the month to `6` the underlying date becomes `2018-07-01` as there is no june 31. You could get the correct result using: 

```php
$date = Chronos::create()->year(2018)->startOfMonth()->month(6)->startOfDay();
debug($date);
```

**Comment by agarzon** [comment]
What about ?

```php
        $now = Time::now();
        $now->year = 2018;
        $now->month = 6;
        debug($now);
```

**Comment by dereuromark** [comment]
No. Without startOfMonth() reset after year setting, the month setter will make the overflow happen.
So better to never use the property setter, but a clean method interface approach.

**Comment by agarzon** [comment]
Now I see where the problem is and why we did not catched before (today is 31th) and why the date must be set as the 1st date before manipulating it.

But still a unexpect thing if you just follow the doc.

Thanks to both.
