### ISSUE TITLE
locale for diffForHumans method

### ISSUE THREAD

**Issue by IndraGunawan** [cakephp/chronos#171]
Hi, there is a way to create another locale used `diffForHumans` method for multi locale site?

**Comment by markstory** [comment]
Yes the [diffFormatter() method](https://github.com/cakephp/chronos/blob/9fed95be5690228bba9f519df518082d3d14ec10/src/Traits/DifferenceTrait.php#L290-L300) allows you to replace the DifferenceFormatter, which contains a `Translator` which does the actual translations.

**Comment by IndraGunawan** [comment]
thank you :)
