### ISSUE TITLE
Accept an Array from datetime Inputs for DateTime::__construct() in MutableDateTime.php

### ISSUE THREAD

**Issue by 3811015** [cakephp/chronos#176]
I leave this for a discussion. 
I think it would be a small enhancement, which is easy to achive and worth it...

Imagine, you are building your own validation rule in cakephp... Let's keep it simple, something like a datatime-field is not permitted to be more than one hour in the future.
You will end up building something like this:

```
$validator->add('begin', 'costum', [
   'rule' => function ($value, $context){
        //Calculate the diff against Time::now()
        //if diff is ok, return true
        return false;
   },
   'message' => __('Der Beginn liegt mehr als eine Stunde in der Zukunft.')
]);
...
return $validator;
```

If you look at $value, you will see an array like:

```
[
	'year' => '2017',
	'month' => '03',
	'day' => '02',
	'hour' => '15',
	'minute' => '30'
]
```

So you can't do following:
```
$valueTime = new Time($value);
$valueDiff = $value->diff(Time::now());
if()...
```

You will need to write your stupid own array to string conversion in this validator. You will need to write your own tests for this array to string conversion. Would be much nicer, to put the array in there and not worrying about all else so much.

Kind regards.

**Comment by saeideng** [comment]
cake uses 
https://github.com/cakephp/cakephp/blob/1f51a72d4b85ab98e0a1dcc195d50565c847724e/src/Validation/Validation.php#L1568-L1591
