### ISSUE TITLE
Dates far the past using MM/dd/YYYY are displayed one year ahead

### ISSUE THREAD

**Issue by sethjohnson1** [cakephp/chronos#178]
I have noticed that when dates toward the turn of the century or before are displayed as MM/dd/YYYY, they appear incorrectly - one year ahead of where they should be. For example 12/31/1889 is saved to the database, and then rendered as 12/31/1890. Obviously this causes problems with CakePHPs edit views, where the values are automatically populated in form controls. Each time the user saves, the date is incremented ahead.

I noticed if I use `Cake\I18n\FrozenDate::setToStringFormat(\IntlDateFormatter::SHORT)` instead of `Cake\I18n\FrozenDate::setToStringFormat('MM/dd/YYYY')` then the dates are displayed correctly.

**Comment by markstory** [comment]
Does your database support saving values formatted with `mm/dd/yyyy`? The date columns I've worked with in the past required `YYYY-MM-DD`.

How can someone reproduce the issue you're having/seeing?

**Comment by lorenzo** [comment]
The format is wrong, please use `yyyy` as uppercase `Y` means "week year" which is a different thing. You can read about the format here http://userguide.icu-project.org/formatparse/datetime

**Comment by sethjohnson1** [comment]
Yes but this happens with the default settings in CakePHP
