### ISSUE TITLE
This library breaks nesbot/carbon version 2.0+

### ISSUE THREAD

**Issue by colinodell** [cakephp/chronos#180]
This library does not seem to be compatible with Carbon 2.0 or higher due to the aliases defined in `src/carbon_compat.php`.  Attempting to use Carbon while this library is installed results in the following fatal error on PHP 7.2:

> PHP Fatal error:  Declaration of Carbon\Carbon::diffInDaysFiltered(Closure $callback, $date = NULL, $absolute = true) must be compatible with Cake\Chronos\ChronosInterface::diffInDaysFiltered(callable $callback, ?Cake\Chronos\ChronosInterface $dt = NULL, $abs = true) in /tmp/chronos/vendor/nesbot/carbon/src/Carbon/Carbon.php on line 489

And this error on PHP 7.1:

> PHP Fatal error:  Declaration of Carbon\Carbon::eq($date): bool must be compatible with Cake\Chronos\ChronosInterface::eq(Cake\Chronos\ChronosInterface $dt) in /tmp/chronos/vendor/nesbot/carbon/src/Carbon/Carbon.php on line 489

I can replicate this by performing the following steps:

1. Clone this repository
2. Run `composer require --dev nesbot/carbon` (installing any version 2.0.0 or higher)
3. Run the following PHP code:

```php
require_once 'vendor/autoload.php';

$d = \Carbon\Carbon::now();
```

I would not expect the presence of one library (Chronos) to completely break another (Carbon).

Commenting-out the last two lines in `src/carbon_compat.php` resolves this issue for me.  Perhaps these lines should only be conditionally executed if Carbon is not present?

**Comment by markstory** [comment]
Closing as a pull request is open to fix this.
