### ISSUE TITLE
No link to api docs from main documentation

### ISSUE THREAD

**Issue by othercorey** [cakephp/chronos#199]
The main documentation has a header that points to the main cake php api/book documentation and not the chronos api documentation.

https://book.cakephp.org/chronos/1.x/en/

You have to open the github readme page to find the link to the api docs.  I think adding it to the side-bar in contents.rst probably makes sense, but I don't know what you intended.

**Comment by markstory** [comment]
Having a link from the docs to the API seems like a good idea to me.

**Comment by saeideng** [comment]
also could be useful to rename `api` to `core api` or something like this in header
PR open ,so closing
