### ISSUE TITLE
Failing tests in WIN OS

### ISSUE THREAD

**Issue by dereuromark** [cakephp/chronos#23]
For fun I tried it on WIN OS:

There were 2 failures:
```
1) Cake\Chronos\Test\DateTime\NowAndOtherStaticHelpersTest::testMinValue with data set "mutable" ('Cake\Chronos\MutableDateTime')
Failed asserting that -214748365 is equal to -2147483647 or is less than -2147483647.

vendor\cakephp\chronos\tests\DateTime\NowAndOtherStaticHelpersTest.php:113
phar://vendor/cakephp/chronos/phpunit.phar/phpunit/TextUI/Command.php:186
phar://vendor/cakephp/chronos/phpunit.phar/phpunit/TextUI/Command.php:138

2) Cake\Chronos\Test\DateTime\NowAndOtherStaticHelpersTest::testMinValue with data set "immutable" ('Cake\Chronos\Chronos')
Failed asserting that -214748365 is equal to -2147483647 or is less than -2147483647.

vendor\cakephp\chronos\tests\DateTime\NowAndOtherStaticHelpersTest.php:113
phar://vendor/cakephp/chronos/phpunit.phar/phpunit/TextUI/Command.php:186
phar://vendor/cakephp/chronos/phpunit.phar/phpunit/TextUI/Command.php:138

FAILURES!
Tests: 992, Assertions: 2765, Failures: 2.
```

Shall we modify the expectation for this to pass?

**Comment by jippi** [comment]
are you sure it just isn't time drift inside the tests?

**Comment by dereuromark** [comment]
It is reproducable so it should be handled in some way.

**Comment by markstory** [comment]
How is windows off by an order of magnitude? Are you on a 32bit install?

**Comment by dereuromark** [comment]
Its 64 bit I tested it on, Win8.

**Comment by ndm2** [comment]
**https://github.com/cakephp/chronos/blob/master/src/FactoryTrait.php#L114**

`PHP_INT_SIZE` will either be `4` (32-Bit) or `8` (64-Bit), but never `32`. So this will always choose the latter expression. And since on Windows even the 64-Bit PHP doesn't actually support 64-Bit integers, `PHP_INT_MAX / 10` will return `214748364.7`.

**Comment by dereuromark** [comment]
What do you propose? checking in Win OS and hardcoding PHP_INT_SIZE to 4 then to be safe?

**Comment by ndm2** [comment]
There should be no need test for the OS (in case that's what you were referring to), just comparing against `4` should do it. On Windows the 64-Bit PHP will return `4`, so this should work fine.
