### ISSUE TITLE
Warning raised if PHP 7.4 preloading is enabled

### ISSUE THREAD

**Issue by alekitto** [cakephp/chronos#249]
Hi and thank you for your work on this library.

I've tried to enable PHP 7.4 preloading feature on one of my projects, everything is working, but the logs are reporting a warning stating that the aliases defined in `carbon_compat.php` are already in use.

This is mainly because that file is blindly included by composer autoload script while preloading classes and in the request entrypoint.

PS: I'm using symfony, the preload script is generated from the framework and I cannot exclude the `vendor/autoload.php` from the script.

**Comment by markstory** [comment]
How do you suggest we work around these warnings to increase compatibility with preloading? I have not use preloading before.

**Comment by alekitto** [comment]
I've opened a PR with a possible work around
