### ISSUE TITLE
Timezone not honored on Date::now or MutableDate::now

### ISSUE THREAD

**Issue by watermark** [cakephp/chronos#252]
# Issue
The timezone parameter is not honored for FactoryTrait function implementations of Date or MutableDate.

# Expectation
Date::now("America/New_York") always gives the current date of the UTC timezone.  Expectation is that it would give the current date of the given timezone.

The timezone parameter is properly honored on all methods in the FactoryTrait for all classes that use that trait.

**Comment by othercorey** [comment]
What version of Chronos are you using?

**Comment by watermark** [comment]
1.3.0.  I thought I was on the latest version, but am only on the latest 1.x release.  I see that 2.0 release notes claims to fix the above issue.  I'll close the issue.  Sorry and thanks.
