### ISSUE TITLE
Date::diffInMonths returns unexpected result in Asia/Tokyo

### ISSUE THREAD

**Issue by chinpei215** [cakephp/chronos#253]
(This issue was originally reported by **kaasan** in Japanese Slack channel)

### What you did

```php
date_default_timezone_set('Asia/Tokyo');

$from = new Date('2019-06-01');
$to = new Date('2019-10-01');

var_dump($from->diffInMonths($to));
```

### What happened

```
int (3)
```

### What you expected to happen

```
int (4)
```

This is not a bug of Chronos actually. I don't know why, but the built-in DateTime/DateTimeImmutable doesn't work correctly either:

```php
date_default_timezone_set('Asia/Tokyo');

$from = new DateTime('2019-06-01');
$to = new DateTime('2019-10-01');

var_dump($from->diff($to)->m);

// int(3)
```

However, as of Chronos 2.x, the timezone of Date will be always fixed to server timezone. Hence, now any methods of Date witch call the diff method internally doesn't work correctly unfortunately.

### Possible solution

A possible solution would be to override the diff method and to use UTC in the method temporarily. Probably, Date and MutableDate can be fixed without any side effects in this way. But if we also try to fix Chronos and MutableDateTime in the same way, it might cause side effects in other timezones, especially during daylight saving time.

**Comment by markstory** [comment]
Does this time range cross the DST boundary for Tokyo? If so you might be an hour short of four months.

**Comment by chinpei215** [comment]
No. DST is not adopted in Japan. In addition, it happens even in winter season. For example:
```php
date_default_timezone_set('Asia/Tokyo');

$from = new DateTime('2019-11-01');
$to = new DateTime('2019-12-01');

var_dump($from->diff($to)->m);
// int(0)
```

It seems like the timezone offset (+09:00 in Japan) is ignored in the diff method.
```php
date_default_timezone_set('Asia/Tokyo');

$from = new DateTime('2019-11-01 09:00');
$to = new DateTime('2019-12-01 09:00');

var_dump($from->diff($to)->m);
// int(1)
```

**Comment by othercorey** [comment]
I submitted a bug report. Hopefully, we get an answer on how diff() is calculated for different time zones.

https://bugs.php.net/bug.php?id=79452

**Comment by othercorey** [comment]
From the php ticket, diff() converts the DateTime objects to UTC before comparing.

This means any time zone change that causes a date change can affect the month calculation. Waiting to see if there is more discussion, but the only solution might be to "fake" the date in UTC before calling diff() to get a consistent result.

**Comment by othercorey** [comment]
Fixed in https://github.com/cakephp/chronos/pull/283
