### ISSUE TITLE
Remove useless aliases

### ISSUE THREAD

**Issue by dereuromark** [cakephp/chronos#29]
Do we really need those (redundant) aliases?

```
@method static ChronosInterval dayz($days = 1) Alias for days()

@property-read int $dayzExcludeWeeks Total days remaining in the final week of the current instance (days % 7).
```

I would remove them in favor of their original properties/methods.

//EDIT
It seems they are used for some reason. Removing them makes quite a few of tests failing (renaming dayz to days)...

**Comment by HavokInspiration** [comment]
In which context are they used ? What is the purpose of using them instead of the original methods ?

**Comment by markstory** [comment]
The methods ending in z should probably be removed - tests included.

**Comment by dereuromark** [comment]
@HavokInspiration That if I knew ;)

@markstory I agree.
I will post the diff tomorrow, but the test results so far aren't promising

**Comment by dereuromark** [comment]
See https://github.com/cakephp/chronos/compare/feature/remove-aliases
The tests don't seem to like it.

**Comment by dereuromark** [comment]
These are the results: https://travis-ci.org/cakephp/chronos/jobs/85077565

**Comment by markstory** [comment]
So I took a look at this, and I think its caused by DateInterval having a `days` property that means something totally different from how we want to use it.

**Comment by dereuromark** [comment]
Interesting. Whats your solution on this then? Keeping the strange dayz thing?

**Comment by markstory** [comment]
The internal storage is `$this->d` only the public interface has `dayz`.
