### ISSUE TITLE
Drop PHP 7.2?

### ISSUE THREAD

**Issue by MGatner** [cakephp/chronos#325]
How important is it to keep support for version 7.2 (https://www.php.net/supported-versions.php)? Without it we could commit fully to PHPUnit 9 and update the schema (https://github.com/cakephp/chronos/runs/8195027937?check_suite_focus=true#step:9:14).

7.1 to 7.2 was a block for some hosting services but 7.3 was pretty much all additions. It looks lie 7.2 installs is down to about 8% (https://packagist.org/packages/cakephp/chronos/php-stats)

**Comment by dereuromark** [comment]
7.3+ sounds fair now.

**Comment by othercorey** [comment]
I don't know that it helps anything. We will move to PHP 8.1 or PHP 8.2 + with Chronos 3.

**Comment by dereuromark** [comment]
Patch Release here helps LTS imo for those majors

**Comment by MGatner** [comment]
I agree. The current version will be just as viable for 7.2 perpetually. Dropping an unsupported minor language version  in a minor release gives a smoother upgrade path. The alternative is forcing developers to make a major language version switch _and_ fix breaking changes from the library in one go.

**Comment by dereuromark** [comment]
You could make a PR

**Comment by othercorey** [comment]
This seems like a pointless change to me.

**Comment by dereuromark** [comment]
If it is only about phpunit, then probably yes

**Comment by MGatner** [comment]
I'm not a maintainer, totally up to you all. For my OSS packages I keep a tighter lower bound to encourage people to get off PHP versions that don't have security support. But I also don't have packages with 27 million downloads.

I think if you decide not to change versions that a roadmap would be helpful; this library would benefit greatly from a `>= 8.0` rework, which could correspond to some of the interface changes in #79.

**Comment by othercorey** [comment]
I appreciate that, but I think this is a case of looking too closely at the problem. We update the requirements as needed to support the project and when it's unmaintainable. This will happen soon enough.

A new release just to change the PHP version doesn't help us yet.
