### ISSUE TITLE
Allow for more expressive comparisons

### ISSUE THREAD

**Issue by dereuromark** [cakephp/chronos#33]
It's easier to quickly understand a line of code by reading `->greaterThan()` than `->gt()`.

I think we should use the non abbr version, and remove the shortcuts.
Less obfuscation.

Refs https://github.com/briannesbitt/Carbon/pull/446

So renaming:

    eq() => equalTo()
    ne() => notEqualTo()
    gt() => greaterThan()    
    lt() => lessThan()
    gte() => greaterThanOrEqualTo()    
    lte() => lessThanOrEqualTo()

It also fits to verbose naming inside cakephp core and other projects like phpunit.

optionally drop aliases for minimum/maximum/timezone:

    min() => already exists as minimum()
    max() => already exists as maximum()
    tz() => already exists as setTimezone() and timezone()!

having too many aliases for no reason is usually sth we are used to from PHP core but shouldn't go down the same rabbit hole IMO.

**Comment by markstory** [comment]
Closing as there is a pull request open now.
