### ISSUE TITLE
Drop src/carbon_compat.php

### ISSUE THREAD

**Issue by ADmad** [cakephp/chronos#331]
Given that the Carbon project is ~~alive~~ undead again I don't think the aliasing is required.

**Comment by othercorey** [comment]
I think users will have to port after this anyway since we won't have the same ABI.

**Comment by markstory** [comment]
Yeah, lets do it. With carbon being maintained again folks who want to use carbon can do that instead if they'd prefer the API. I think this is also an opportune time for us to revisit the width of the API we expose in chronos. Do we really need *all* the formatting methods? Are there are a few we should keep and simplify the API by removing the rest?

**Comment by ADmad** [comment]
> Do we really need all the formatting methods? Are there are a few we should keep and simplify the API by removing the rest?

Indeed, the current API is huge, we should look into trimming it down.

**Comment by othercorey** [comment]
closed in https://github.com/cakephp/chronos/pull/332
