### ISSUE TITLE
Trim down the ChronosInterface's API

### ISSUE THREAD

**Issue by ADmad** [cakephp/chronos#335]
Currently `ChronosInterface` has a pretty large API surface.

Multiple methods have both singular and plural form. With IDE autocompletion these days no one needs to remember whether the singular or plural form needs to be used. So all singular forms can be dropped.

- `add/subYear()`
- `add/subYearWithOverflow()`
- `add/subYearWithoutOverflow()`
- `add/subMonth()`
- `add/subMonthWithOverflow()`
- `add/subMonthWithoutOverflow()`
- `add/subDay()`
- `add/subWeekDay()`
- `add/subWeek()`
- `add/subHour()`
- `add/subMinute()`
- `add/subSecond()`

Following methods potentially have very limited usage and could be dropped:
- `is{Day}` for each day for the the week
- `start/endOfDecade()`
- `start/endOfCentury()`

There are various methods which are short aliases of longer/full method names, e.g. `eq()`, `tz()` etc. Personally I am undecided ~~where~~ whether we should keep or drop the short aliases.

**Comment by othercorey** [comment]
Removing the singular API seems straight forward.

**Comment by markstory** [comment]
I agree with @othercorey. These are safe removes that help reduce API bloat.

> Personally I am undecided where we should keep or drop the short aliases.

We should pick a side. My bias is to use the longer names so that we don't have short-form soup for an API.

**Comment by othercorey** [comment]
The short names were the original API  and the long names were added a couple years ago. I don't want to remove `equals()` in favor of `eq()` though.

**Comment by ADmad** [comment]
Seems the general consensus is in favor of keeping the long names. So I'll make a PR dropping the short ones.

**Comment by ADmad** [comment]
I would also like to drop the over a dozen `to{X}String()` methods. We can keep just `__toString()` and for other format users can use `format()`.

**Comment by markstory** [comment]
Could we keep the toXString method that do commonly used formats like ISO-8601?

**Comment by ADmad** [comment]
I don't want to be the judge of which ones are commonly used and which ones aren't :slightly_smiling_face:. I am gonna leave them as they are.

**Comment by othercorey** [comment]
Going to close because the proposed changes were made.
