### ISSUE TITLE
Chronos3: BC handling with native type/interface

### ISSUE THREAD

**Issue by dereuromark** [cakephp/chronos#377]
Since Chronos now doesnt implement the native interface anymore, we now need to inline alias the DateTime class:
```php
use Cake\I18n\DateTime;
use DateTime as NativeDateTime;

...
$offset = $timezone->getOffset(new NativeDateTime('@' . mktime(0, 0, 0, 2, 1, (int)date('Y'))));
```

getOffset() needs the native one here, as do quite a few other methods

If we dont plan on using a more native interface implementation, we might want to provide a method to easily get one if needed, e.g. `->toNative()` or alike:
```
$offset = $timezone->getOffset($dateTime->toNative());
```

**Comment by markstory** [comment]
> we might want to provide a method to easily get one if needed, e.g. ->toNative() or alike:

Having a `toNative()` method sounds like a good idea to me.
