### ISSUE TITLE
False Statement in 2.x Docs about Timezone Fixation

### ISSUE THREAD

**Issue by ravage84** [cakephp/chronos#385]
Both, the documentation for the version 1.x & 2.x state:

>  The time and timezone for these objects is always fixed to 00:00:00 UTC [...]

https://book.cakephp.org/chronos/1/en/index.html#date-objects
https://book.cakephp.org/chronos/2/en/index.html#date-objects

While this seems to be true for Chronos 1.x:

- CakePHP 3.10.5
- CakePHP Chronos 1.3.0
- ``$config['App']['defaultTimezone'] = 'Europe/Zurich';``

```` bash
Psy Shell v0.11.14 (PHP 7.4.33 — cli) by Justin Hileman
New version is available at psysh.org/psysh (current: v0.11.14, latest: v0.11.15)
> use Cake\Chronos\Date;
> $today = Date::today();
= Cake\Chronos\Date @1681430400 {#2871
    hasFixedNow: false,
    date: 2023-04-14 00:00:00.0 UTC (+00:00),
  }

> $today->modify('+1 hours');
= Cake\Chronos\Date @1681430400 {#2871
    hasFixedNow: false,
    date: 2023-04-14 00:00:00.0 UTC (+00:00),
  }
````

=> ``2023-04-14 00:00:00.0 UTC (+00:00)``

It apparently isn't true (anymore) for Chronos 2.x:

- CakePHP 4.4.12
- CakePHP Chronos 2.3.2
- ``$config['App']['defaultTimezone'] = 'Europe/Zurich';``

```` bash
Psy Shell v0.11.12 (PHP 7.4.33 — cli) by Justin Hileman
New version is available at psysh.org/psysh (current: v0.11.12, latest: v0.11.15)
> use Cake\Chronos\Date;
> $today = Date::today();
= Cake\Chronos\Date @1681423200 {#2884
    hasFixedNow: false,
    date: 2023-04-14 00:00:00.0 Europe/Zurich (+02:00),
  }

> $today->modify('+1 hours');
= Cake\Chronos\Date @1681423200 {#2884
    hasFixedNow: false,
    date: 2023-04-14 00:00:00.0 Europe/Zurich (+02:00),
  }
````

=> ``2023-04-14 00:00:00.0 Europe/Zurich (+02:00))``

Is this a documenatation error or  is some detail missing which could explain the observed behavior?

We noticed this change in behavior when we investigated a failing test assertion after upgrading from CakePHP 3.10.x to CakePHP 4.4.x.
Interestingly, this seemed to fix some invalid behavior of Chronos 1.x, as the test assertion was previously expecting some illogic value (a day before the actual date).

**Comment by markstory** [comment]
> Is this a documenatation error or is some detail missing which could explain the observed behavior?

This sounds like incorrect behavior. The timezone for date should be fixed to UTC.

**Comment by markstory** [comment]
Looks like this was an intentional change made in #218 so that `today()` and `now()` could be called for specific timezones. Correcting the docs seems like the safest solution here as the behavior change was intentional and during a major release.
