### ISSUE TITLE
Hello, I would like to create a Java program for Windows 10 that has a button which, when clicked, starts a timer and that when it approaches minutes 10, 11, 12, and 13, opens a pop-up window with large text and an alarm sound. Can anyone help me with the code or point me in the right direction to get started?

### ISSUE THREAD

**Issue by RikAlc23** [cakephp/chronos#387]
Hello, I would like to create a Java program for Windows 10 that has a button which, when clicked, starts a timer and that when it approaches minutes 10, 11, 12, and 13, opens a pop-up window with large text and an alarm sound. Can anyone help me with the code or point me in the right direction to get started?

_Originally posted by @RikAlc23 in https://github.com/cakephp/chronos/issues/386#issuecomment-1510326560_

**Comment by LordSimal** [comment]
This is a PHP repository which has nothing to do with java. I hid your comment from the related PR because it has nothing to do with the PR. Please use google or find a java related support forum where you can ask questions about java.
