### ISSUE TITLE
Some deprecation warnings since 2.4.0

### ISSUE THREAD

**Issue by markusramsak** [cakephp/chronos#404]
calling timezone() instead of setTimezone() for example causes a lot of deprecation Warning wenn calling i.e. ->i18nFormat('...', ['timezone' => 'Europe/Vienna']);

**Comment by ADmad** [comment]
Duplicate https://github.com/cakephp/cakephp/issues/17223

**Comment by othercorey** [comment]
We released out of order unfortunately. You can restrict Chronos in your composer.json until a new cakephp version is released.
