### ISSUE TITLE
Method endOfDay disregarding microseconds

### ISSUE THREAD

**Issue by brenoroosevelt** [cakephp/chronos#416]
Hi.

I've noticed a minor issue that I would like to discuss and suggest some improvements. The Chronos::endOf[Day|Month|Week|...] modifier methods seem to be disregarding microseconds. This can cause problems in cases where microsecond precision is important.
```php
Chronos::now()->endOfDay(); //  2023-09-30 23:59:59.000000
```

- Expected:  2023-09-30 23:59:59.**999999**
- Got:  2023-09-30 23:59:59.**000000**

**Proposal:**

 1. **Adjustment of the `endOfDay` method:**
 ```php
   public function endOfDay(): static
   {
       return $this->modify('23:59:59.999999');
   }
```

 2. The idea is to leverage the `endOfDay` method in other modifiers, ensuring that microseconds are consistently considered. For example, in the `endOfMonth` method:
```php
public function endOfMonth(): static
{
    return $this->modify('last day of this month')->endOfDay();
}
```

 3. Addition of an `isEndOfDay` comparator method:
```php
public function isEndOfDay($checkMicrosecond = true): bool
{
    return ...;
}
```
I've also been thinking that it might be beneficial to provide other comparators like isLastDayOfMonth, etc., but there are so many possibilities that it might be better to implement the Specification pattern:
```php
interface ChronosSpecification
{
   public function isSatisfiedBy(Chronos $date): bool;
}
```
```php
class Chronos 
{
   //...
   public function is(ChronosSpecification $specification): bool
   {
   	return $specification->isSatisfiedBy($this);
   }
}
```
```php
class LastDayOfMonth implements ChronosSpecification
{
    public function isSatisfiedBy(Chronos $date): bool
    {
    	return $date->daysInMonth === $date->day;
    }
}
```
Both the library and the user could benefit from this pattern:
```php
Chronos::now()->is(new LastDayOfMonth());
Chronos::now()->is(new MyEnrollmentPeriod());
```
This would be a significant improvement, but the main focus is to adjust the end of the day to consider microseconds.

Thank you for your attention to this matter, and I look forward to your feedback and possible enhancements.

**Comment by othercorey** [comment]
Setting microseconds is probably correct here. 

Applications might not care about microseconds and compare directly to a time they set which includes seconds only so this might be a breaking change more than a bug fix.

@markstory thoughts?

**Comment by markstory** [comment]
> Applications might not care about microseconds and compare directly to a time they set which includes seconds only so this might be a breaking change more than a bug fix.

This is my concern as well. Setting the microtime is probably ok, but changing the `startX` and `endX` comparison methods to consider microseconds will very likely cause trouble for application code.

> Applications might not care about microseconds and compare directly to a time they set which includes seconds only so this might be a breaking change more than a bug fix.

This is an interesting idea, and gives us a path to not have to continually expand API surface for new comparisons, and provides an extensible system for developers to use.
