### ISSUE TITLE
Method toNative() has gone missing

### ISSUE THREAD

**Issue by shadowhand** [cakephp/chronos#432]
https://github.com/cakephp/chronos/pull/417#pullrequestreview-1652711214

According to Semantic Versioning, methods and attributes MAY NOT be removed except in major releases. The `toNative()` method was present in versions 3.0.0 and 3.0.1, but removed in 3.0.2. This breaks expectations and trust in versioning.

**Comment by dereuromark** [comment]
Yes that removal was invalid, but got corrected
https://github.com/cakephp/chronos/pull/427
Are u sure it is gone in your downloaded code and the actual release?

**Comment by shadowhand** [comment]
100% positive that it is missing in version 3.0.2.

**Comment by dereuromark** [comment]
Ah, chronos class itself it is still missing

**Comment by shadowhand** [comment]
According to PR #417 it was removed in Chronos, ChronosDate, and ChronosTime. According to PR #427 it was only restored to ChronosDate and ChronosTime.

And yes, I have confirmed that the released package 3.0.2 does NOT have `Chronos::toNative()` method.

**Comment by dereuromark** [comment]
Pr open, will be released asap!

**Comment by shadowhand** [comment]
Thanks for the quick resolution!
