### ISSUE TITLE
2.4.x: addSecond() is deprecated. Use addSeconds()

### ISSUE THREAD

**Issue by SaeedSalem** [cakephp/chronos#437]
I get this error:

Since 2.4 - addSecond() is deprecated. Use addSeconds() instead. at /var/www/vendor/cakephp/chronos/src/Traits/ModifierTrait.php:863

**Comment by othercorey** [comment]
You need to change your code to call `addSeconds(value)`

**Comment by SaeedSalem** [comment]
I'm sorry, the error was in laravel/horizon package.
They are using addSecond().

**Comment by dereuromark** [comment]
You can always silence deprecations. They are not "hard errors", but information on how to improve code for future compatibility.
