### ISSUE TITLE
ISO 8601: Missing colon in timezone

### ISSUE THREAD

**Issue by dereuromark** [cakephp/chronos#44]
Shouldn't the toIso8601String() method have an colon between the hours and minutes in the timezone part?
1975-12-25T14:15:16-0500 becomes 1975-12-25T14:15:16-05:00

Spec: http://www.w3.org/TR/NOTE-datetime

Refs https://github.com/briannesbitt/Carbon/issues/451

**Comment by markstory** [comment]
We're using the [PHP constant](http://php.net/manual/en/class.datetime.php#datetime.constants.iso8601) The chances of that being wrong seem pretty low.

**Comment by dereuromark** [comment]
There is a note below that linked documentation:

> Note: This format is not compatible with ISO-8601, but is left this way for backward compatibility reasons. Use DateTime::ATOM or DATE_ATOM for compatibility with ISO-8601 instead.

**Comment by dereuromark** [comment]
So either we fix it ourselves (add the colon) or should promote using the outlined formats.

**Comment by ADmad** [comment]
> This format is not compatible with ISO-8601, but is left this way for backward compatibility reasons.

Heh, so someone made a mistake initially and instead of fixing it they decided to stick with it. PHP is full of funnies.

**Comment by markstory** [comment]
Bloody Hell. Well, we can use ATOM instead of ISO8601

**Comment by markstory** [comment]
Pull request up.
