### ISSUE TITLE
Invalid deprecation error for Date::startOfWeek()

### ISSUE THREAD

**Issue by jurchiks** [cakephp/chronos#453]
I just updated my installation of Chronos to the latest available version for the project (PHP 7.3, so best I get is 2.4.4), and I got this nonsensical error:
`(new Date($anyDateHere))->addWeeks(1)->startOfWeek()`
throws
`2.5 startOfDay() will be removed in 3.x.`
But this method calls `startOfDay()` implicitly, under the hood, users can't NOT call it.

**Comment by othercorey** [comment]
@markstory What do you think?

**Comment by ravage84** [comment]
`startOfDay()` just does `return $this->modify('midnight');`.

So why not do that where `startOfDay()`  is currently called?

**Comment by ravage84** [comment]
Same for `endOfDay()`, by the way.
