### ISSUE TITLE
addWeekday(s) clears time

### ISSUE THREAD

**Issue by dereuromark** [cakephp/chronos#54]
Check if
https://github.com/briannesbitt/Carbon/commit/d02c4136c3300e5044226e5be8fcfc5b4b6fc272
needs to be applied

Refs https://github.com/briannesbitt/Carbon/issues/419

**Comment by lorenzo** [comment]
@dereuromark would you like to copy the fix from them?

**Comment by dereuromark** [comment]
It seems that their fix only was for addWeekday. addWeekdays as well as the sub methods also need fixing i guess.
Additionally, the fixes cannot be applied without some modification for us: https://github.com/cakephp/chronos/compare/master-weekday
Tests failing.

**Comment by markstory** [comment]
@dereuromark Those changes seem reasonable. For the immutable objects, you'll need to capture the return of `modify()` and chain off of that instead.

**Comment by dereuromark** [comment]
You are absolutely right. Done :)
