### ISSUE TITLE
Find out if we can/need to workaround PHP bug

### ISSUE THREAD

**Issue by dereuromark** [cakephp/chronos#62]
See https://github.com/briannesbitt/Carbon/issues/539 and https://bugs.php.net/bug.php?id=63863

DateTime:setDate() date not used after modify("last day of...")

**Comment by HavokInspiration** [comment]
Apparently there is a simple workaround given at the end of the PHP bug tracker ticket : https://bugs.php.net/bug.php?id=63863#1446180347

(Last comment).
Maybe it is worth trying it ?

**Comment by dereuromark** [comment]
Wasnt there already some simililar issue - like in https://github.com/cakephp/chronos/pull/58/files ?

**Comment by nicholas-eden** [comment]
I can verify that the workaround mentioned in that bug report works:
https://github.com/briannesbitt/Carbon/pull/542/files

**Comment by markstory** [comment]
Pull request open now.
