### ISSUE TITLE
RFC Datetime and Date class name

### ISSUE THREAD

**Issue by dereuromark** [cakephp/chronos#71]
The more I use it and think about it the more sense it would make to have a consistent naming scheme for the class names.
```php
//Currently
$time = new Chronos('2015-10-21 16:29:00');
$date = new Date('2015-10-21');
$time = new MutableDateTime('2015-10-21 16:29:00');
$date = new MutableDate('2015-10-21');

// Prosposed
$time = new DateTime('2015-10-21 16:29:00');
$date = new Date('2015-10-21');
$time = new MutableDateTime('2015-10-21 16:29:00');
$date = new MutableDate('2015-10-21');
```

Afaik the only reason was namespace clashing/confusion.
But with all the other 3 classes around I think the confusion is rather internal now, with Chronos not just as namespace but also as class name sticking out here.
`Chronos` also does not say anything about the type of date it contains or can work on ( is it Date, or DateTime or just Time or ...). For me that is a cool package name, but not a very explaning class name.
Thus I think **DateTime** would indeed be the more sane name for the Chronos class IMO.

We can change it now before releasing a 1.0.0.

**Comment by lorenzo** [comment]
That could potentially be painful for end users, since using both \DateTime and Chronos\DateTime in the same class would require aliasing.

**Comment by dereuromark** [comment]
And the other 3 don't have a core PHP counterpart you mean?

**Comment by lorenzo** [comment]
Yeah, that's what I mean... In general I don't like class names to be repeated, even if we have namespaces, because reading the code becomes more difficult

**Comment by dereuromark** [comment]
In that case pre- or suffixing is usually the way to go, but `ChronosDateTime` could become a little bit much to write maybe?

**Comment by josegonzalez** [comment]
What about:

```php
class Chronos extends Chronos\DateTime
```

That way users that want to just use the Chronos version can, and all others can use the Chronos name.

**Comment by dereuromark** [comment]
That sounds like a fair (and BC) compromise.

**Comment by antograssiot** [comment]
PR #74 is open so discution can take place there.
