### ISSUE TITLE
Chronos Date can be corrupted by PHP DatePeriod

### ISSUE THREAD

**Issue by nyamsprod** [cakephp/chronos#76]
The time for the `Chronos\Date` objects is corrupted by `DatePeriod`.

Here's a simple script to reproduce the bug:

``` php
$startDate = Cake\Chronos\Date::yesterday();
$endDate = Cake\Chronos\Date::tomorrow();
$datePeriod = new DatePeriod($startDate, new DateInterval('PT12H'), $endDate);
foreach ($datePeriod as $date) {
    echo get_class($date), ' => ', $date->format('Y-m-d H:i:s'), PHP_EOL;
}
```

I expected either : 

``` bash
Cake\Chronos\Date => 2016-01-31 00:00:00
Cake\Chronos\Date => 2016-01-31 00:00:00
Cake\Chronos\Date => 2016-02-01 00:00:00
Cake\Chronos\Date => 2016-02-01 00:00:00
```

or an **exception** to be thrown but I got this instead

``` bash
Cake\Chronos\Date => 2016-01-31 00:00:00
Cake\Chronos\Date => 2016-01-31 12:00:00
Cake\Chronos\Date => 2016-02-01 00:00:00
Cake\Chronos\Date => 2016-02-01 12:00:00
```

**Comment by markstory** [comment]
Nice find! I'll take a look.

**Comment by markstory** [comment]
I'm not sure this can be fixed. I took a [look at the php-src](https://github.com/php/php-src/blob/c343d3fae5e36d36d73ca40bf19607879c7783ff/ext/date/php_date.c#L1877-L1897). From what I can understand it looks like the internals of `DatePeriod` creates new instances and directly assigns private properties.

Outside of breaking compatibility with `DatePeriod` by not extending `DateTime` I don't know how we could solve this.

**Comment by wouterj** [comment]
How is this a bug? If you have a period of 12 hours and start at 00:00, it is expected to have 12:00 next, followed by 00:00, followed by 12:00, right? PHP's DateTime behaves exactly the same: https://3v4l.org/Om7v2

**Comment by nyamsprod** [comment]
@wouterj it is a bug because as stated in the documentation https://book.cakephp.org/3.0/en/chronos.html#date-objects  the `Date` object strips the time part so it should not be possible to have an instance with time part which is different from `00:00:00.000000`
