### ISSUE TITLE
Add Semester

### ISSUE THREAD

**Issue by dereuromark** [cakephp/chronos#83]
Refs https://github.com/briannesbitt/Carbon/pull/611

to be API compliant.

**Comment by markstory** [comment]
I dunno about 'semester'. In Canada we have 3 semesters not 2.

**Comment by dereuromark** [comment]
Please see https://en.wiktionary.org/wiki/semester
The technical term is from latin and refers to 6 months, those in canada should probably be called trimester :)
Anyway, if we don't like it we should probably downvote them in Carbon early on to not have to shim them in the long run.

**Comment by lorenzo** [comment]
Yeah, unfortunately semester can have different meanings depending on the culture.

**Comment by jadb** [comment]
@markstory, aren't those period more akin to the collegial naming? Or is this like a standard for defining these specific 4-months period length? 

Side note, in french (`semestre`), refers to a 6 months period too.

**Comment by markstory** [comment]
I'm ok with being wrong on this one :smile: If 'semester' has a common meaning I'm :+1: for including it.

**Comment by jadb** [comment]
I never said I was right! :wink: I ask because you are more knowledgeable of Canadian standards and I wanted to learn :smile:.

**Comment by ADmad** [comment]
I believe the most common time period for semester would be 6 months.

**Comment by dereuromark** [comment]
Yep, it sure is 6 months by default.
But closing since the original Carbon one was also closed, and therefore no need here for this edge case thing :)
