### ISSUE TITLE
Set locale for diffForHumans

### ISSUE THREAD

**Issue by hecerinc** [cakephp/chronos#84]
I've been trying to get locale-specific strings for `diffForHumans` à-la Carbon, but can't seem to get it to work. Is this feature implemented?. Tried `I18n:locale()` and PHP's `setlocale` but no good.

**Comment by lorenzo** [comment]
What language are you missing? Currently the repo only contains the translations for english and all the infrastructure to offer you own translations. We could investigate porting the translated strings out of carbon

**Comment by hecerinc** [comment]
I was looking for Spanish... I'll take a look into it and submit a PR if possible

**Comment by lorenzo** [comment]
@hecerinc did you need help for adding the locale?

**Comment by tm1000** [comment]
This is actually the one thing I need for my project. My project supports multiple languages so it would be nice to get that setLocale function from Carbon (http://carbon.nesbot.com/docs/#api-localization) back with the translated strings. I would be willing to work on it..

**Comment by tm1000** [comment]
It looks like all I need to do is change Translator::$strings. I can actually present that to my translators if you think thats maybe a better way to go instead of migrating the translations from Carbon..... but... the work was already done...

```
public static $strings = [
        'year' => '1 year',
        'year_plural' => '{count} years',
        'month' => '1 month',
        'month_plural' => '{count} months',
        'week' => '1 week',
        'week_plural' => '{count} weeks',
        'day' => '1 day',
        'day_plural' => '{count} days',
        'hour' => '1 hour',
        'hour_plural' => '{count} hours',
        'minute' => '1 minute',
        'minute_plural' => '{count} minutes',
        'second' => '1 second',
        'second_plural' => '{count} seconds',
        'ago' => '{time} ago',
        'from_now' => '{time} from now',
        'after' => '{time} after',
        'before' => '{time} before',
    ];
```

**Comment by lorenzo** [comment]
@tm1000 that looks like a good plan to me! Sorry for the late response

**Comment by Oxicode** [comment]
+1

**Comment by tm1000** [comment]
Hi all I am still planning on getting to this if anyone was curious.

**Comment by lorenzo** [comment]
@tm1000 go for it!
