### ISSUE TITLE
first day of week and week number 

### ISSUE THREAD

**Issue by makamo** [cakephp/chronos#89]
Is there a way to set Sunday as the first day of the week and get the week number accordingly

i got a issu on carbon for reference 

https://github.com/briannesbitt/Carbon/pull/214

**Comment by lorenzo** [comment]
No, there currently no way of doing that.

**Comment by dereuromark** [comment]
Please provide a PR to make it possible to adjust this if you find the time. Would be greatly appreciated.

**Comment by othercorey** [comment]
PHP also considers Monday as the start of week now.

https://www.php.net/manual/en/datetime.formats.relative.php

>5.6.23, 7.0.8 | Weeks always start on monday. Formerly, sunday would also be considered to start a week.
