### ISSUE TITLE
diffInMonths not calculating based on calendar months

### ISSUE THREAD

**Issue by jtrumbull** [cakephp/chronos#94]
This might be an issue of interpretation rather than a bug, however the difference in months is not calculating the actual number of calendar months between two dates, and is causing unexpected results.

Take the following, for example, which is comparing the last day of a month to the last day of the following month:

``` php
$date1 = new MutableDate('2016-01-01');
$date1->endOfMonth();
$date2 = new MutableDate('2016-01-01');
$i = 12;

while ($i--) {

  $date2->addMonth(1)->endOfMonth();

  echo $date1->format('m/d/Y')." -> ";
  echo $date2->format('m/d/Y')." = ";
  echo $date1->diffInMonths($date2)."\n";

  $date1->addMonth(1)->endOfMonth();

}
```

I would expect this to produce `1`s across the board, however it produces:

```
01/31/2016 -> 02/29/2016 = 0
02/29/2016 -> 03/31/2016 = 1
03/31/2016 -> 04/30/2016 = 0
04/30/2016 -> 05/31/2016 = 1
05/31/2016 -> 06/30/2016 = 0
06/30/2016 -> 07/31/2016 = 1
07/31/2016 -> 08/31/2016 = 1
08/31/2016 -> 09/30/2016 = 0
09/30/2016 -> 10/31/2016 = 1
10/31/2016 -> 11/30/2016 = 0
11/30/2016 -> 12/31/2016 = 1
12/31/2016 -> 01/31/2017 = 1
```

When the day in the 1st month is greater than the number of day of the 2nd month, the month difference is interpreted as `0` -even when it's the last day of the month. I'm assuming this is by design to prevent from:

```
01/31/2016 -> 02/01/2016 = 1
```

Would it make sense to change the logic of `diffInMonths` to represent the difference in calendar months, or add a new method to the `DifferenceTrait`:

``` php
public function diffInCalendarMonths(ChronosInterface $dt = null)
{
  $dt = $dt === null ? static::now($this->tz) : $dt;
  return (($dt->year - $this->year) * ChronosInterface::MONTHS_PER_YEAR) + ($dt->month - $this->month);
}
```

**Comment by markstory** [comment]
I think adding a new method might be best, as `DateTime::diff()` has a well understood if a bit wonky behavior.

**Comment by vlakoff** [comment]
It's also about [`DateInterval::format()`](http://php.net/manual/en/dateinterval.format.php), which just doesn't know the month thus the number of days.

+1 for this proposal, as it is more predictible and less surprising. I'd bend for modifying the existing method (doesn't seem breaking) rather than adding a new one (much clutter, wow).

**Comment by digilist** [comment]
I am very +1 for having a feature that calculates the diff based on calendar months.

However, I would not change the current method, as it is a BC break. I cannot know if anybody needs this method and wants this behavior, so changing it should be a no-go.

**Comment by markstory** [comment]
Adding a new method name is always an option to generate differences based on calendar months.

**Comment by othercorey** [comment]
```
  return (($dt->year - $this->year) * ChronosInterface::MONTHS_PER_YEAR) + ($dt->month - $this->month);
```

I don't think this would give the user what they want either.  This would result in 2019-01-31 and 2019-02-01 showing 1 month difference.
